// Traductions anglaises du contenu du site.
//
// Ce fichier est ecrit par `pnpm run en:translate`, qui tourne aussi avant
// chaque build. Il ne contient que des phrases deja traduites: le site les
// repose telles quelles, sans appeler personne. C'est ce qui evite de rejouer
// la traduction entiere du site dans chacun des processus qui fabriquent les
// pages.
//
// La cle est le texte francais exact, tel qu'il sort du Studio. Les titres de
// section et la premiere ligne du pied de page sont recolles avant d'etre
// cherches ("Comment ca" + "marche"), la cle est donc la phrase entiere.
//
// Corriger une traduction a la main ici est sans danger: le script ne remplace
// jamais une ligne existante, il ne fait qu'ajouter les phrases nouvelles et
// retirer celles qui ne sont plus affichees nulle part.

export const TRADUCTIONS_EN = {
  "À prévoir": "What to bring",
  "Accompagnement et animation": "Guide and entertainment",
  "Accompagnement et encadrement par notre équipe": "Support and supervision by our team",
  "Accompagnement et organisation": "Support and organisation",
  "Agadir": "Agadir",
  "Agence de voyage 100% femmes au Maroc | EcoTrips Women": "100% women's travel agency in Morocco | EcoTrips Women",
  "Agence de voyages organisés 100% femmes au Maroc": "Organized travel agency for women only in Morocco",
  "Aghroud": "Aghroud",
  "Al Hoceïma": "Al Hoceïma",
  "Ambiances de voyage": "Travel vibes",
  "Annulation gratuite": "Free cancellation",
  "Arrivée sur la côte, installation, plages de Taghazout et d'Aghroud.": "Arrival on the coast, check-in, beaches of Taghazout and Aghroud.",
  "Aucun voyage ne correspond à ta recherche.": "No trip matches your search.",
  "Avis Google": "Google reviews",
  "Belyounech": "Belyounech",
  "Bon à savoir": "Good to know",
  "Caravane de dromadaires traversant les dunes orangées": "Camel caravan crossing the orange dunes",
  "Carte d'identité": "ID card",
  "Casablanca": "Casablanca",
  "Ce que racontent les femmes qui sont déjà parties avec EcoTrips Women.": "What the women who have already travelled with EcoTrips Women say.",
  "Ce qui est compris": "What's included",
  "Change complet": "Complete change of clothes",
  "Chaussures confortables": "Comfortable shoes",
  "Choisis ton voyage": "Choose your trip",
  "Comment ça marche": "How it works",
  "Comment réserver une place ?": "How to book a spot?",
  "Comment se passe un voyage organisé entre femmes au Maroc ?": "How does an organized trip between women work in Morocco?",
  "Communauté": "Community",
  "Confirme ta place, ton départ et les infos pratiques.": "Confirm your spot, departure and practical info.",
  "Crème solaire": "Sun cream",
  "Crème solaire et chapeau": "Sunscreen and hat",
  "Départ de Tanger (06h00 devant la mosquée des Syriens) puis de Tétouan (07h00 devant la gare CTM/Routière).\nPetit-déjeuner à Amsa et pause à Jebha.\nArrivée à Al Hoceima : balade en bateau optionnelle (150 DHS, 1h30) pour visiter 7 plages et grottes avec pause thé et baignade dans des eaux cristallines. Détente à la plage Quemado avec temps libre pour les activités nautiques.\nDéjeuner, puis route en soirée vers Nador pour l'installation à l'hôtel (City Center) et le dîner.": "Departure from Tangier (06:00 in front of the Syrians Mosque) then from Tetouan (07:00 in front of the CTM/Bus station).\nBreakfast in Amsa and break in Jebha.\nArrival in Al Hoceima: optional boat tour (150 DHS, 1h30) to visit 7 beaches and caves with a tea break and swimming in crystal clear waters. Relaxation at Quemado beach with free time for water activities.\nLunch, then evening drive to Nador for hotel check-in (City Center) and dinner.",
  "Départ en soirée le 03 septembre, route de nuit en bus touristique.": "Evening departure on 03 September, overnight travel by tourist bus.",
  "Départ selon l'offre: Tanger, Tétouan, Rabat ou Salé.": "Departure depending on the offer: Tangier, Tetouan, Rabat or Salé.",
  "Départ Tanger - Tétouan": "Departure Tangier - Tetouan",
  "Depuis le bouton Réserver de n'importe quel voyage. Tu remplis un court formulaire (prénom, nom, ville de départ, téléphone, date souhaitée), puis WhatsApp s'ouvre avec ton message déjà rédigé. L'équipe te recontacte pour confirmer ta place.": "From the Book button on any trip. You fill out a short form (first name, last name, departure city, phone, desired date), then WhatsApp opens with your message already written. The team will contact you back to confirm your spot.",
  "Depuis quelles villes partent vos voyages organisés ?": "Which cities do your organized trips depart from?",
  "Deux nuitées d'hébergement dans un hôtel au centre-ville de Nador": "Two nights accommodation in a downtown hotel in Nador",
  "Deux petits-déjeuners à l'hôtel": "Two breakfasts at the hotel",
  "Deux voyageuses dans le jardin fleuri d'une maison d'hôtes": "Two travellers in the flowery garden of a guesthouse",
  "Deux voyageuses devant le panneau du Jbel Boujmil": "Two travellers in front of the Jbel Boujmil sign",
  "Deux voyageuses formant un cœur avec leurs mains devant la montagne enneigée": "Two travellers making a heart shape with their hands in front of the snow-capped mountain",
  "EcoTrips au fil des voyages": "EcoTrips across trips",
  "EcoTrips peut t'emmener loin": "EcoTrips can take you far",
  "EcoTrips Women est une agence de voyage féminine au Maroc : voyages organisés 100% femmes, en petits groupes, au départ de Tanger, Tétouan, Rabat et Salé. Transport, hébergement et accompagnement inclus.": "EcoTrips Women is a women's travel agency in Morocco: 100% women's organized trips in small groups, departing from Tangier, Tetouan, Rabat and Salé. Transport, accommodation and support included.",
  "Écrire sur WhatsApp": "Write on WhatsApp",
  "Envoyer ma réservation": "Send my booking",
  "Essaouira": "Essaouira",
  "explorer le Maroc": "explore Morocco",
  "Fonds marins et poissons observés pendant une plongée": "Seabed and fish observed during a dive",
  "Groupe de voyageuses en été devant le rocher champignon": "Group of travellers in summer in front of the mushroom rock",
  "Groupes féminins, ambiance bienveillante et accompagnement.": "Women's groups, friendly atmosphere and support.",
  "Hébergement 2 nuits": "2 nights' accommodation",
  "image": "image",
  "Imsouane": "Imsouane",
  "Jour 1 - Départ, découverte d'Al Hoceima et route vers Nador": "Day 1 - Departure, discovery of Al Hoceima and drive to Nador",
  "Jour 1 · Départ le soir": "Day 1 · Evening departure",
  "Jour 2 - Les joyaux de Nador : Cara Blanca, Tibouda et Tcharrana": "Day 2 - The jewels of Nador: Cara Blanca, Tibouda and Tcharrana",
  "Jour 2 · Taghazout et Aghroud": "Day 2 · Taghazout and Aghroud",
  "Jour 3 - Plage thermale Hmam Chaabi et retour": "Day 3 - Thermal beach Hmam Chaabi and return",
  "Jour 3 · Imsouane et Timlaline": "Day 3 · Imsouane and Timlaline",
  "Jour 4 · Essaouira et retour": "Day 4 · Essaouira and return",
  "Journée · Plongée et village": "Day · Diving and village",
  "Journée entre la baie d'Imsouane et Timlaline, villages et bord de mer.": "Day between the bay of Imsouane and Timlaline, villages and seaside.",
  "Jusqu'à 7 jours avant le départ, remboursement intégral.": "Up to 7 days before departure, full refund.",
  "La balade en bateau à Al Hoceima (150 DHS)": "The boat trip in Al Hoceima (150 DHS)",
  "Le groupe au sommet du Jbel Karbou, à 1618 mètres": "The group at the summit of Jbel Karbou, at 1618 metres",
  "Le groupe autour du 4x4 au milieu des dunes": "The group around the 4x4 in the middle of the dunes",
  "Le groupe brandissant le drapeau EcoTrips Women dans la neige": "The group holding up the EcoTrips Women flag in the snow",
  "Le groupe de voyageuses salue la caméra sur la falaise au bord de la mer": "The group of travellers waving to the camera on the cliff by the sea",
  "Le groupe EcoTrips Women devant le rocher champignon au bord de la mer": "The EcoTrips Women group in front of the mushroom rock by the sea",
  "Le groupe en randonnée sur les collines verdoyantes": "The group hiking on the green hills",
  "Le groupe posant sur la falaise devant le rocher champignon": "The group posing on the cliff in front of the mushroom rock",
  "Le même voyage, la fois précédente": "The same trip, last time",
  "Le programme": "The programme",
  "Les activités nautiques (Jet ski, kayak...) et barques optionnelles": "Water activities (Jet ski, kayak...) and optional boats",
  "Les avis de nos voyageuses": "Our travellers' reviews",
  "Les photos rapportées par le groupe lors de la dernière édition.": "Photos taken by the group during the last edition.",
  "Les repas (déjeuners et dîners)": "Meals (lunches and dinners)",
  "Maillot de bain et serviette": "Swimsuit and towel",
  "Matin · Départ et arrivée à Belyounech": "Morning · Departure and arrival in Belyounech",
  "Mer, camping, randonnée ou week-end détente.": "Sea, camping, hiking or relaxing weekend.",
  "Moments de voyage": "Travel moments",
  "Nador": "Nador",
  "Nador - Houceima": "Nador - Al Hoceima",
  "Nature et mer": "Nature and sea",
  "Nos départs se font depuis Tanger, Tétouan, Rabat et Salé, selon le voyage choisi. La ville de départ est indiquée sur chaque offre, et le filtre par ville de la page Toutes les offres permet de ne voir que les voyages qui partent de chez toi.": "Our departures are from Tangier, Tetouan, Rabat and Salé, depending on the chosen trip. The departure city is indicated on each offer, and the city filter on the All offers page lets you see only the trips departing from near you.",
  "Offres actives": "Active offers",
  "on t'aide à": "we help you",
  "Oui, et c'est très courant. Tu réserves ta place seule et tu rejoins le groupe de voyageuses au départ. Tu peux aussi réserver pour plusieurs personnes : le formulaire demande alors le prénom et le nom de chaque participante.": "Yes, and it's very common. You book your spot alone and join the group of travellers at departure. You can also book for several people: the form then asks for the first and last name of each participant.",
  "Oui. EcoTrips Women organise uniquement des voyages 100% femmes, en petits groupes. C'est le principe même de l'agence : voyager entre femmes, dans une ambiance bienveillante.": "Yes. EcoTrips Women exclusively organizes 100% women's trips in small groups. That's the very principle of the agency: travelling between women in a friendly atmosphere.",
  "Paiement flexible": "Flexible payment",
  "Partage tes souvenirs": "Share your memories",
  "Petit-déjeuner à l'hôtel. Départ vers Cara Blanca : pour votre confort, un transport en voiture (inclus) vous évitera la longue marche (seulement 10 min de marche restante) pour atteindre la célèbre roche \"Coupe du Monde\". Baignade dans des eaux limpides et shooting photo. \nDéjeuner au village de Tibouda, baignade et balade en barque optionnelle vers Cap des 3 Fourches/Minarouzia. \nFin de journée à la plage de Tcharrana pour un magnifique coucher de soleil. Retour à l'hôtel, temps libre et dîner à Nador.": "Breakfast at the hotel. Departure towards Cara Blanca: for your comfort, car transport (included) will save you the long walk (only 10 min walk remaining) to reach the famous \"World Cup\" rock. Swimming in clear waters and photo shoot.\nLunch in the village of Tibouda, swimming and optional boat trip to Cap des 3 Fourches/Minarouzia.\nEnd of day at Tcharrana beach for a magnificent sunset. Return to hotel, free time and dinner in Nador.",
  "Petit-déjeuner matinal à l'hôtel. Direction la plage Hmam Chaabi (accès 100% réservé aux femmes la matinée jusqu'à 14h00), réputée pour ses eaux chaudes aux vertus thérapeutiques pour la peau. Déjeuner à Boukidan (Al Hoceima), puis route du retour vers Tétouan et Tanger avec quelques pauses en chemin.": "Early breakfast at the hotel. Head to Hmam Chaabi beach (access 100% reserved for women in the morning until 14:00), renowned for its warm waters with therapeutic properties for the skin. Lunch in Boukidan (Al Hoceima), then return drive to Tetouan and Tangier with a few stops along the way.",
  "Peut-on réserver seule ?": "Can I book alone?",
  "Photos et vidéos GoPro": "GoPro photos and videos",
  "Photos et vidéos prises pendant nos sorties. Clique pour agrandir.": "Photos and videos taken during our outings. Click to enlarge.",
  "Photos, vidéos, souvenirs et nouvelles amitiés.": "Photos, videos, memories and new friendships.",
  "Places limitées": "Limited places",
  "Plages, randonnées, piscine, camping et villages côtiers.": "Beaches, hikes, swimming pool, camping and coastal villages.",
  "Plongée Belyounech": "Belyounech diving",
  "Plongée sous-marine": "Scuba diving",
  "Plongée sous-marine encadrée, puis visite du village de Belyounech. Photos et vidéos GoPro tout au long de la sortie.": "Supervised scuba diving, then visit of the Belyounech village. GoPro photos and videos throughout the outing.",
  "Plongeuse formant un cœur avec ses mains sous l'eau": "Female diver making a heart shape with her hands underwater",
  "Plus d'infos": "More info",
  "Pour recevoir les prochaines sorties ou réserver une place, contacte directement l'équipe.": "To receive upcoming outings or book a spot, contact the team directly.",
  "Prochains départs": "Upcoming departures",
  "Prochains voyages": "Upcoming trips",
  "Qu'est-ce qui est compris dans le prix d'un voyage femme au Maroc ?": "What is included in the price of a women's trip in Morocco?",
  "Quatre jours sur la côte atlantique : Agadir,Taghazout, Essaouira, Imsouane, Aghroud et Timlaline. Plages, villages de pêcheurs et médina, avec hébergement et transport touristique inclus.": "Four days on the Atlantic coast: Agadir, Taghazout, Essaouira, Imsouane, Aghroud and Timlaline. Beaches, fishing villages and medina, with accommodation and tourist transport included.",
  "Questions fréquentes": "Frequently asked questions",
  "Rabat/Salé": "Rabat/Salé",
  "Randonnée du groupe dans la neige avec bâtons de marche": "Group hiking in the snow with walking poles",
  "Rejoignez-nous pour une aventure inédite entre nature enchanteresse et mer paisible. Un voyage pensé pour les femmes, afin de découvrir les plus belles plages du Royaume, dont la célèbre et atypique plage Hmam Chaabi, réputée pour ses sources thermales.": "Join us for a unique adventure between enchanting nature and peaceful sea. A trip designed for women to discover the Kingdom's most beautiful beaches, including the famous and atypical Hmam Chaabi beach, renowned for its hot springs.",
  "Rejoins-nous sur Instagram": "Join us on Instagram",
  "Remplis ces quelques informations : elles partent directement à l'équipe, qui te recontacte pour confirmer ta place.": "Fill in this few information: it goes directly to the team, who will contact you back to confirm your spot.",
  "Rendez-vous le matin à Tanger puis à Tétouan, route vers Belyounech et accueil par l'équipe.": "Meeting in the morning in Tangier then in Tetouan, drive to Belyounech and welcome by the team.",
  "Réservation directe par WhatsApp avec l'équipe EcoTrips.": "Direct booking via WhatsApp with the EcoTrips team.",
  "Réserve sur WhatsApp": "Book on WhatsApp",
  "Réserver ce voyage": "Book this trip",
  "Réserver sur WhatsApp": "Book on WhatsApp",
  "Retour vers Tétouan et Tanger en fin de journée.": "Return to Tétouan and Tanger at the end of the day.",
  "Scanne le QR code ou clique dessus pour ouvrir la page Instagram EcoTrips Women.": "Scan the QR code or click on it to open the EcoTrips Women Instagram page.",
  "Selon l'offre : le transport aller-retour en bus touristique, l'hébergement, les petits déjeuners, les visites et activités prévues au programme, et l'accompagnement par l'équipe. Le détail exact figure dans la rubrique « Ce qui est compris » de chaque voyage.": "Depending on the offer: round-trip transport in a tourist bus, accommodation, breakfasts, visits and activities planned in the programme, and support from the team. Exact details can be found in the \"What's included\" section of each trip.",
  "She can travel !": "She can travel !",
  "Simple et rassurant": "Simple and reassuring",
  "Soir · Retour": "Evening · Return",
  "Souvenirs": "Memories",
  "Surf Taghazout": "Taghazout surf",
  "Taghazout": "Taghazout",
  "Taghazout - Essaouira": "Taghazout - Essaouira",
  "Tanger": "Tangier",
  "Téléphérique Agadir": "Agadir cable car",
  "Tes informations ne servent qu'à traiter ta réservation. Tu pourras nous écrire sur WhatsApp juste après si tu as une question.": "Your details are only used to process your booking. You can message us on WhatsApp right after if you have a question.",
  "Tétouan": "Tetouan",
  "Tétouan - Tanger - Rabat/Salé - Casablanca": "Tétouan - Tanger - Rabat/Salé - Casablanca",
  "Timlalin Canyons": "Timlalin Canyons",
  "Timlaline": "Timlaline",
  "Tous les départs": "All departures",
  "Tous les voyages": "All trips",
  "Tous nos voyages organisés 100% femmes au Maroc. Filtre par ville de départ, prix, mois, durée ou destination.": "All our 100% women's organized trips in Morocco. Filter by departure city, price, month, duration or destination.",
  "Tout ce qu'on nous demande avant un premier voyage organisé entre femmes.": "Everything you ask us before your first organized trip between women.",
  "Toutes nos offres": "All our offers",
  "Transport aller-retour": "Return transport",
  "Transport aller-retour en bus touristique": "Round-trip transport in a tourist bus",
  "Transport inclus": "Transport included",
  "Transport local (voitures) aller-retour pour la plage de Cara Blanca": "Round-trip local transport (cars) to Cara Blanca beach",
  "Transport touristique": "Tourist transport",
  "Transport touristique, activités et groupe féminin.": "Tourist transport, activities and women's group.",
  "Tu choisis ton voyage parmi les départs à venir, tu réserves ta place en quelques informations, puis tu pars en petit groupe 100% féminin. Le transport touristique, l'hébergement et l'accompagnement par l'équipe EcoTrips Women sont organisés de bout en bout : tu n'as rien à préparer d'autre que ton sac.": "You choose your trip from the upcoming departures, book your spot with a few details, then head off in a 100% female small group. Tourist transport, accommodation and support by the EcoTrips Women team are organized from start to finish: you don't need to prepare anything other than your bag.",
  "Tu choisis ton voyage, EcoTrips Women gère les détails essentiels.": "You choose your trip, EcoTrips Women handles the essential details.",
  "Une journée de plongée sous-marine à Belyounech, le dimanche 16 août, au départ de Tanger et Tétouan. Découverte des fonds marins, visite du village et photos souvenir en GoPro. Promotion à 399 DH au lieu de 500 DH.": "A day of scuba diving in Belyounech, on Sunday August 16, departing from Tangier and Tetouan. Discovery of the seabed, visit of the village and GoPro souvenir photos. Special offer at 399 DH instead of 500 DH.",
  "Une question avant de réserver ?": "A question before booking?",
  "Verse 500 DH d'avance aujourd'hui, le reste avant le départ.": "Pay an advance of 500 DH today, the rest before departure.",
  "video": "video",
  "Vidéo souvenir d'une sortie EcoTrips Women": "Souvenir video of an EcoTrips Women outing",
  "Vidéo souvenir dans les dunes du désert": "Souvenir video in the desert dunes",
  "Vidéos de voyageuses": "Traveller videos",
  "Visite de 4 plages à Nador et 1 plage à Al Hoceima": "Visit of 4 beaches in Nador and 1 beach in Al Hoceima",
  "Visite de la médina et du port d'Essaouira, puis retour.": "Visit to the medina and port of Essaouira, then return.",
  "Visite du village de Belyounech": "Visit to the village of Belyounech",
  "Visites (plages, villages…)": "Visits (beaches, villages...)",
  "Voir les départs": "View departures",
  "Voir toutes les offres": "View all offers",
  "Vos voyages sont-ils réservés aux femmes ?": "Are your trips reserved for women?",
  "Voyage accompagnée": "Accompanied travel",
  "Voyages 100% femmes au Maroc, organisés avec transport, activités et accompagnement.": "100% women's trips in Morocco, organized with transport, activities and support.",
  "Voyages à venir": "Upcoming trips",
  "Voyages entre femmes": "Trips between women",
  "Voyageuse allongée sur une dune à côté du drapeau EcoTrips Women": "Traveller lying on a dune next to the EcoTrips Women flag",
  "Voyageuse au sommet du Toubkal en hiver": "Traveller at the summit of Toubkal in winter",
  "Voyageuse en combinaison de ski dans la neige": "Traveller in a ski suit in the snow",
  "Voyageuse posant au panneau du sommet du Jbel Karbou": "Traveller posing by the Jbel Karbou summit sign",
  "Voyageuse sur un pont au-dessus d'une rivière turquoise": "Traveller on a bridge over a turquoise river",
  "Voyageuse sur un pont au-dessus d'une rivière turquoise en montagne": "Traveller on a bridge over a turquoise river in the mountains",
  "Voyageuses réunies au sommet du Monte Blanco face à la baie": "Travellers gathered at the top of Monte Blanco overlooking the bay",
  "Voyageuses satisfaites": "Satisfied travellers",
};
