// Traductions anglaises du contenu du site.
//
// Ce fichier est ecrit par `pnpm run en:translate`, qui tourne aussi avant
// chaque build. Il ne contient que des phrases deja traduites: le site les
// repose telles quelles, sans appeler personne. C'est ce qui evite de rejouer
// la traduction entiere du site dans chacun des processus qui fabriquent les
// pages.
//
// La cle est le texte francais exact, tel qu'il sort du Studio. Les titres de
// section et la premiere ligne du pied de page sont recolles avant d'etre
// cherches ("Comment ca" + "marche"), la cle est donc la phrase entiere.
//
// Corriger une traduction a la main ici est sans danger: le script ne remplace
// jamais une ligne existante, il ne fait qu'ajouter les phrases nouvelles et
// retirer celles qui ne sont plus affichees nulle part.

export const TRADUCTIONS_EN = {
  "À prévoir": "What to bring",
  "Accompagnement et animation": "Guide and entertainment",
  "Accompagnement et encadrement par notre équipe": "Support and supervision by our team",
  "Accompagnement, organisation et encadrement par notre équipe": "Support, organization and supervision by our team",
  "Agadir": "Agadir",
  "Agence de voyage 100% femmes au Maroc | EcoTrips Women": "100% women's travel agency in Morocco | EcoTrips Women",
  "Agence de voyages organisés 100% femmes au Maroc": "Organized travel agency for women only in Morocco",
  "Aghroud": "Aghroud",
  "Al Hoceïma": "Al Hoceïma",
  "Ambiances de voyage": "Travel vibes",
  "Annulation gratuite": "Free cancellation",
  "Après le petit-déjeuner, journée consacrée à la visite de la ville d'Essaouira : flânerie dans l'ancienne médina, balade sur les remparts et découverte du port de pêche. Voyage de retour vers vos villes de départ en fin de journée.": "After breakfast, a day dedicated to visiting the city of Essaouira: wandering through the old medina, walking along the ramparts and discovering the fishing port. Return journey to your departure cities at the end of the day.",
  "Arrivée sur la côte atlantique, installation à l'hébergement (à Tamraght) et découverte des plages. Au programme de la journée : visite d'Agadir, de la station balnéaire de Taghazout et du célèbre village coloré d'Aghroud.": "Arrival on the Atlantic coast, check-in at the accommodation (in Tamraght) and discovery of the beaches. On the day's agenda: visit Agadir, the seaside resort of Taghazout and the famous colorful village of Aghroud.",
  "Aucun voyage ne correspond à ta recherche.": "No trip matches your search.",
  "Avis Google": "Google reviews",
  "Belyounech": "Belyounech",
  "Bon à savoir": "Good to know",
  "Caravane de dromadaires traversant les dunes orangées": "Camel caravan crossing the orange dunes",
  "Carte d'identité": "ID card",
  "Casablanca": "Casablanca",
  "Ce que racontent les femmes qui sont déjà parties avec EcoTrips Women.": "What the women who have already travelled with EcoTrips Women say.",
  "Ce qui est compris": "What's included",
  "Change complet": "Complete change of clothes",
  "Chaussures confortables": "Comfortable shoes",
  "Choisis ton voyage": "Choose your trip",
  "Comment ça marche": "How it works",
  "Comment réserver une place ?": "How to book a spot?",
  "Comment se passe un voyage organisé entre femmes au Maroc ?": "How does an organized trip between women work in Morocco?",
  "Communauté": "Community",
  "Confirme ta place, ton départ et les infos pratiques.": "Confirm your spot, departure and practical info.",
  "Crème solaire": "Sun cream",
  "Crème solaire et chapeau": "Sunscreen and hat",
  "Début de l'expérience de plongée encadrée, à tour de rôle, avec prise de photos et vidéos professionnelles. Temps libre pour se baigner et profiter de la plage de Belyounech, suivi d'une pause déjeuner dans un restaurant face à la mer (repas non inclus).": "Start of the supervised diving experience, in turn, with professional photos and video shooting. Free time to swim and enjoy the beach in Belyounech, followed by a lunch break at a seafront restaurant (meal not included).",
  "Départ de Tanger (06h00 devant la mosquée des Syriens) puis de Tétouan (07h00 devant la gare CTM/Routière).\nPetit-déjeuner à Amsa et pause à Jebha.\nArrivée à Al Hoceima : balade en bateau optionnelle (150 DHS, 1h30) pour visiter 7 plages et grottes avec pause thé et baignade dans des eaux cristallines. Détente à la plage Quemado avec temps libre pour les activités nautiques.\nDéjeuner, puis route en soirée vers Nador pour l'installation à l'hôtel (City Center) et le dîner.": "Departure from Tangier (06:00 in front of the Syrians Mosque) then from Tetouan (07:00 in front of the CTM/Bus station).\nBreakfast in Amsa and break in Jebha.\nArrival in Al Hoceima: optional boat tour (150 DHS, 1h30) to visit 7 beaches and caves with a tea break and swimming in crystal clear waters. Relaxation at Quemado beach with free time for water activities.\nLunch, then evening drive to Nador for hotel check-in (City Center) and dinner.",
  "Départ en soirée et route de nuit en bus touristique.\n\nTétouan : À 20h00 devant l'agence CTM Chellal.\n\nTanger : À 21h00 devant la Mosquée des Syriens.\n\nRabat / Salé : Possibilité de rejoindre le groupe à Sala Al Jadida.\n\nCasablanca : Possibilité de rejoindre le groupe à Tit Mellil.": "Evening departure and overnight drive by tourist bus.\n\nTétouan: At 20:00 in front of the CTM Chellal agency.\n\nTanger: At 21:00 in front of the Mosque of the Syrians.\n\nRabat / Salé: Option to join the group in Sala Al Jadida.\n\nCasablanca: Option to join the group in Tit Mellil.",
  "Départ selon l'offre: Tanger, Tétouan, Rabat ou Salé.": "Departure depending on the offer: Tangier, Tetouan, Rabat or Salé.",
  "Départ Tanger - Tétouan": "Departure Tangier - Tetouan",
  "Depuis le bouton Réserver de n'importe quel voyage. Tu remplis un court formulaire (prénom, nom, ville de départ, téléphone, date souhaitée), puis WhatsApp s'ouvre avec ton message déjà rédigé. L'équipe te recontacte pour confirmer ta place.": "From the Book button on any trip. You fill out a short form (first name, last name, departure city, phone, desired date), then WhatsApp opens with your message already written. The team will contact you back to confirm your spot.",
  "Depuis quelles villes partent vos voyages organisés ?": "Which cities do your organized trips depart from?",
  "Deux nuitées d'hébergement dans un hôtel au centre-ville de Nador": "Two nights accommodation in a downtown hotel in Nador",
  "Deux petits-déjeuners à l'hôtel": "Two breakfasts at the hotel",
  "Deux voyageuses dans le jardin fleuri d'une maison d'hôtes": "Two travellers in the flowery garden of a guesthouse",
  "Deux voyageuses devant le panneau du Jbel Boujmil": "Two travellers in front of the Jbel Boujmil sign",
  "Deux voyageuses formant un cœur avec leurs mains devant la montagne enneigée": "Two travellers making a heart shape with their hands in front of the snow-capped mountain",
  "EcoTrips au fil des voyages": "EcoTrips across trips",
  "EcoTrips peut t'emmener loin": "EcoTrips can take you far",
  "EcoTrips Women est une agence de voyage féminine au Maroc : voyages organisés 100% femmes, en petits groupes, au départ de Tanger, Tétouan, Rabat et Salé. Transport, hébergement et accompagnement inclus.": "EcoTrips Women is a women's travel agency in Morocco: 100% women's organized trips in small groups, departing from Tangier, Tetouan, Rabat and Salé. Transport, accommodation and support included.",
  "Écrire sur WhatsApp": "Write on WhatsApp",
  "Envoyer ma réservation": "Send my booking",
  "Équipement de plongée complet fourni": "Complete diving equipment provided",
  "Essaouira": "Essaouira",
  "Expérience de plongée avec un moniteur spécialisé": "Diving experience with a specialized instructor",
  "explorer le Maroc": "explore Morocco",
  "Fin de l'excursion et route du retour vers Tanger et Tétouan, avec une arrivée prévue aux alentours de 17h00.": "End of the trip and return drive to Tanger and Tétouan, with an expected arrival around 17:00.",
  "Fonds marins et poissons observés pendant une plongée": "Seabed and fish observed during a dive",
  "Groupe de voyageuses en été devant le rocher champignon": "Group of travellers in summer in front of the mushroom rock",
  "Groupes féminins, ambiance bienveillante et accompagnement.": "Women's groups, friendly atmosphere and support.",
  "Hébergement pour 2 nuitées (Tamraght et Essaouira)": "Accommodation for 2 nights (Tamraght and Essaouira)",
  "image": "image",
  "Imsouane": "Imsouane",
  "Jour 1 - Départ le soir (Jeudi 03 septembre)": "Day 1 - Evening departure (Thursday 03 September)",
  "Jour 1 - Départ, découverte d'Al Hoceima et route vers Nador": "Day 1 - Departure, discovery of Al Hoceima and drive to Nador",
  "Jour 2 - Agadir, Taghazout et Aghroud": "Day 2 - Agadir, Taghazout and Aghroud",
  "Jour 2 - Les joyaux de Nador : Cara Blanca, Tibouda et Tcharrana": "Day 2 - The jewels of Nador: Cara Blanca, Tibouda and Tcharrana",
  "Jour 3 - Imsouane et Timlaline": "Day 3 - Imsouane and Timlaline",
  "Jour 3 - Plage thermale Hmam Chaabi et retour": "Day 3 - Thermal beach Hmam Chaabi and return",
  "Jour 4 · Essaouira et retour": "Day 4 · Essaouira and return",
  "Journée - Expérience de plongée et détente": "Full Day - Diving Experience & Relaxation",
  "Journée d'exploration entre la magnifique baie d'Imsouane (célèbre spot de surf) et les impressionnantes dunes et gorges de Timlaline plongeant dans l'océan. Dîner et nuitée à Essaouira.": "Day of exploration between the magnificent bay of Imsouane (famous surf spot) and the impressive dunes and gorges of Timlaline plunging into the ocean. Dinner and overnight stay in Essaouira.",
  "Jusqu'à 7 jours avant le départ, remboursement intégral.": "Up to 7 days before departure, full refund.",
  "La balade en bateau à Al Hoceima (150 DHS)": "The boat trip in Al Hoceima (150 DHS)",
  "Le groupe au sommet du Jbel Karbou, à 1618 mètres": "The group at the summit of Jbel Karbou, at 1618 metres",
  "Le groupe autour du 4x4 au milieu des dunes": "The group around the 4x4 in the middle of the dunes",
  "Le groupe brandissant le drapeau EcoTrips Women dans la neige": "The group holding up the EcoTrips Women flag in the snow",
  "Le groupe de voyageuses salue la caméra sur la falaise au bord de la mer": "The group of travellers waving to the camera on the cliff by the sea",
  "Le groupe EcoTrips Women devant le rocher champignon au bord de la mer": "The EcoTrips Women group in front of the mushroom rock by the sea",
  "Le groupe en randonnée sur les collines verdoyantes": "The group hiking on the green hills",
  "Le groupe posant sur la falaise devant le rocher champignon": "The group posing on the cliff in front of the mushroom rock",
  "Le même voyage, la fois précédente": "The same trip, last time",
  "Le programme": "The programme",
  "Les activités nautiques (Jet ski, kayak...) et barques optionnelles": "Water activities (Jet ski, kayak...) and optional boats",
  "Les activités optionnelles (Surf, Quad, Sandboarding, balade à dos de chameau, équitation, téléphérique)": "Optional activities (Surf, Quad, Sandboarding, camel ride, horseback riding, cable car)",
  "Les avis de nos voyageuses": "Our travellers' reviews",
  "Les photos rapportées par le groupe lors de la dernière édition.": "Photos taken by the group during the last edition.",
  "Les repas (déjeuners et dîners)": "Meals (lunches and dinners)",
  "Maillot de bain et serviette": "Swimsuit and towel",
  "Matin · Départ et arrivée à Belyounech": "Morning · Departure and arrival in Belyounech",
  "Mer, camping, randonnée ou week-end détente.": "Sea, camping, hiking or relaxing weekend.",
  "Moments de voyage": "Travel moments",
  "Nador": "Nador",
  "Nador - Houceima": "Nador - Al Hoceima",
  "Nature et mer": "Nature and sea",
  "Nos départs se font depuis Tanger, Tétouan, Rabat et Salé, selon le voyage choisi. La ville de départ est indiquée sur chaque offre, et le filtre par ville de la page Toutes les offres permet de ne voir que les voyages qui partent de chez toi.": "Our departures are from Tangier, Tetouan, Rabat and Salé, depending on the chosen trip. The departure city is indicated on each offer, and the city filter on the All offers page lets you see only the trips departing from near you.",
  "Offres actives": "Active offers",
  "on t'aide à": "we help you",
  "Oui, et c'est très courant. Tu réserves ta place seule et tu rejoins le groupe de voyageuses au départ. Tu peux aussi réserver pour plusieurs personnes : le formulaire demande alors le prénom et le nom de chaque participante.": "Yes, and it's very common. You book your spot alone and join the group of travellers at departure. You can also book for several people: the form then asks for the first and last name of each participant.",
  "Oui. EcoTrips Women organise uniquement des voyages 100% femmes, en petits groupes. C'est le principe même de l'agence : voyager entre femmes, dans une ambiance bienveillante.": "Yes. EcoTrips Women exclusively organizes 100% women's trips in small groups. That's the very principle of the agency: travelling between women in a friendly atmosphere.",
  "Paiement flexible": "Flexible payment",
  "Partage tes souvenirs": "Share your memories",
  "Petit-déjeuner à l'hôtel. Départ vers Cara Blanca : pour votre confort, un transport en voiture (inclus) vous évitera la longue marche (seulement 10 min de marche restante) pour atteindre la célèbre roche \"Coupe du Monde\". Baignade dans des eaux limpides et shooting photo. \nDéjeuner au village de Tibouda, baignade et balade en barque optionnelle vers Cap des 3 Fourches/Minarouzia. \nFin de journée à la plage de Tcharrana pour un magnifique coucher de soleil. Retour à l'hôtel, temps libre et dîner à Nador.": "Breakfast at the hotel. Departure towards Cara Blanca: for your comfort, car transport (included) will save you the long walk (only 10 min walk remaining) to reach the famous \"World Cup\" rock. Swimming in clear waters and photo shoot.\nLunch in the village of Tibouda, swimming and optional boat trip to Cap des 3 Fourches/Minarouzia.\nEnd of day at Tcharrana beach for a magnificent sunset. Return to hotel, free time and dinner in Nador.",
  "Petit-déjeuner matinal à l'hôtel. Direction la plage Hmam Chaabi (accès 100% réservé aux femmes la matinée jusqu'à 14h00), réputée pour ses eaux chaudes aux vertus thérapeutiques pour la peau. Déjeuner à Boukidan (Al Hoceima), puis route du retour vers Tétouan et Tanger avec quelques pauses en chemin.": "Early breakfast at the hotel. Head to Hmam Chaabi beach (access 100% reserved for women in the morning until 14:00), renowned for its warm waters with therapeutic properties for the skin. Lunch in Boukidan (Al Hoceima), then return drive to Tetouan and Tangier with a few stops along the way.",
  "Peut-on réserver seule ?": "Can I book alone?",
  "Photos et vidéos prises pendant nos sorties. Clique pour agrandir.": "Photos and videos taken during our outings. Click to enlarge.",
  "Photos et vidéos professionnelles (GoPro)": "Professional photos and videos (GoPro)",
  "Photos, vidéos, souvenirs et nouvelles amitiés.": "Photos, videos, memories and new friendships.",
  "Places limitées": "Limited places",
  "Plages, randonnées, piscine, camping et villages côtiers.": "Beaches, hikes, swimming pool, camping and coastal villages.",
  "Plongée Belyounech": "Belyounech diving",
  "Plongée sous-marine": "Scuba diving",
  "Plongeuse formant un cœur avec ses mains sous l'eau": "Female diver making a heart shape with her hands underwater",
  "Plus d'infos": "More info",
  "Pour recevoir les prochaines sorties ou réserver une place, contacte directement l'équipe.": "To receive upcoming outings or book a spot, contact the team directly.",
  "Prochains départs": "Upcoming departures",
  "Prochains voyages": "Upcoming trips",
  "Qu'est-ce qui est compris dans le prix d'un voyage femme au Maroc ?": "What is included in the price of a women's trip in Morocco?",
  "Questions fréquentes": "Frequently asked questions",
  "Rabat/Salé": "Rabat/Salé",
  "Randonnée du groupe dans la neige avec bâtons de marche": "Group hiking in the snow with walking poles",
  "Rejoignez-nous pour une aventure inédite entre nature enchanteresse et mer paisible. Un voyage pensé pour les femmes, afin de découvrir les plus belles plages du Royaume, dont la célèbre et atypique plage Hmam Chaabi, réputée pour ses sources thermales.": "Join us for a unique adventure between enchanting nature and peaceful sea. A trip designed for women to discover the Kingdom's most beautiful beaches, including the famous and atypical Hmam Chaabi beach, renowned for its hot springs.",
  "Rejoins-nous sur Instagram": "Join us on Instagram",
  "Remplis ces quelques informations : elles partent directement à l'équipe, qui te recontacte pour confirmer ta place.": "Fill in this few information: it goes directly to the team, who will contact you back to confirm your spot.",
  "Rendez-vous et départ de Tétouan à 07h30 (devant la gare CTM) puis de Tanger à 08h30 (devant la Mosquée des Syriens). Arrivée à Belyounech, essayage des combinaisons de plongée (fournies) et briefing détaillé par nos plongeurs professionnels sur les consignes de sécurité à suivre.": "Meet-up and departure from Tétouan at 07:30 (in front of the CTM bus station) then from Tanger at 08:30 (in front of the Mosque of the Syrians). Arrival in Belyounech, fitting of the wetsuits (provided) and detailed briefing by our professional divers on safety rules to follow.",
  "Réservation directe par WhatsApp avec l'équipe EcoTrips.": "Direct booking via WhatsApp with the EcoTrips team.",
  "Réserve sur WhatsApp": "Book on WhatsApp",
  "Réserver ce voyage": "Book this trip",
  "Réserver sur WhatsApp": "Book on WhatsApp",
  "Scanne le QR code ou clique dessus pour ouvrir la page Instagram EcoTrips Women.": "Scan the QR code or click on it to open the EcoTrips Women Instagram page.",
  "Selon l'offre : le transport aller-retour en bus touristique, l'hébergement, les petits déjeuners, les visites et activités prévues au programme, et l'accompagnement par l'équipe. Le détail exact figure dans la rubrique « Ce qui est compris » de chaque voyage.": "Depending on the offer: round-trip transport in a tourist bus, accommodation, breakfasts, visits and activities planned in the programme, and support from the team. Exact details can be found in the \"What's included\" section of each trip.",
  "She can travel !": "She can travel !",
  "Si vous cherchez un voyage alliant plages enchanteresses, villages paisibles, ambiance estivale et villes côtières de caractère, rejoignez-nous pour une nouvelle aventure à la découverte du Sud marocain ! 🌊🏄‍♀️🌅 Quatre jours sur la côte atlantique : Agadir, Taghazout, Essaouira, Imsouane, Aghroud et Timlaline. Un programme 100% féminin, riche en activités, avec hébergement et transport touristique inclus.": "If you are looking for a trip combining enchanting beaches, peaceful villages, summer vibes and coastal towns with character, join us for a new adventure to discover Southern Morocco! 🌊🏄‍♀️🌅 Four days on the Atlantic coast: Agadir, Taghazout, Essaouira, Imsouane, Aghroud and Timlaline. A 100% female programme, packed with activities, with accommodation and tourist transport included.",
  "Simple et rassurant": "Simple and reassuring",
  "Soir · Retour": "Evening · Return",
  "Souvenirs": "Memories",
  "Surf Taghazout": "Taghazout surf",
  "Taghazout": "Taghazout",
  "Taghazout - Essaouira": "Taghazout - Essaouira",
  "Tanger": "Tangier",
  "Téléphérique Agadir": "Agadir cable car",
  "Tes informations ne servent qu'à traiter ta réservation. Tu pourras nous écrire sur WhatsApp juste après si tu as une question.": "Your details are only used to process your booking. You can message us on WhatsApp right after if you have a question.",
  "Tétouan": "Tetouan",
  "Tétouan - Tanger - Rabat/Salé - Casablanca": "Tétouan - Tanger - Rabat/Salé - Casablanca",
  "Timlalin Canyons": "Timlalin Canyons",
  "Timlaline": "Timlaline",
  "Tous les départs": "All departures",
  "Tous les voyages": "All trips",
  "Tous nos voyages organisés 100% femmes au Maroc. Filtre par ville de départ, prix, mois, durée ou destination.": "All our 100% women's organized trips in Morocco. Filter by departure city, price, month, duration or destination.",
  "Tout ce qu'on nous demande avant un premier voyage organisé entre femmes.": "Everything you ask us before your first organized trip between women.",
  "Toutes nos offres": "All our offers",
  "Transport aller-retour en bus touristique": "Round-trip transport in a tourist bus",
  "Transport inclus": "Transport included",
  "Transport local (voitures) aller-retour pour la plage de Cara Blanca": "Round-trip local transport (cars) to Cara Blanca beach",
  "Transport touristique aller-retour confortable": "Comfortable return tourist transport",
  "Transport touristique confortable": "Comfortable tourist transport",
  "Transport touristique, activités et groupe féminin.": "Tourist transport, activities and women's group.",
  "Tu choisis ton voyage parmi les départs à venir, tu réserves ta place en quelques informations, puis tu pars en petit groupe 100% féminin. Le transport touristique, l'hébergement et l'accompagnement par l'équipe EcoTrips Women sont organisés de bout en bout : tu n'as rien à préparer d'autre que ton sac.": "You choose your trip from the upcoming departures, book your spot with a few details, then head off in a 100% female small group. Tourist transport, accommodation and support by the EcoTrips Women team are organized from start to finish: you don't need to prepare anything other than your bag.",
  "Tu choisis ton voyage, EcoTrips Women gère les détails essentiels.": "You choose your trip, EcoTrips Women handles the essential details.",
  "Une journée de plongée sous-marine à Belyounech, exclusivement réservée aux femmes (100% 🎀). Découvrez les fonds marins en toute sécurité, profitez de la plage et repartez avec des photos et vidéos GoPro souvenirs. (Également disponible chaque dimanche et en semaine sur réservation).": "A scuba diving day in Belyounech, exclusively for women (100% 🎀). Discover the seabed in total safety, enjoy the beach and go home with souvenir GoPro photos and videos. (Also available every Sunday and on weekdays upon booking).",
  "Une question avant de réserver ?": "A question before booking?",
  "Verse 500 DH d'avance aujourd'hui, le reste avant le départ.": "Pay an advance of 500 DH today, the rest before departure.",
  "video": "video",
  "Vidéo souvenir d'une sortie EcoTrips Women": "Souvenir video of an EcoTrips Women outing",
  "Vidéo souvenir dans les dunes du désert": "Souvenir video in the desert dunes",
  "Vidéos de voyageuses": "Traveller videos",
  "Visite d'Agadir, Taghazout, Aghroud, Timlaline, Imsouane et Essaouira": "Visit to Agadir, Taghazout, Aghroud, Timlaline, Imsouane and Essaouira",
  "Visite de 4 plages à Nador et 1 plage à Al Hoceima": "Visit of 4 beaches in Nador and 1 beach in Al Hoceima",
  "Visite du village de Belyounech": "Visit to the village of Belyounech",
  "Voir les départs": "View departures",
  "Voir toutes les offres": "View all offers",
  "Vos voyages sont-ils réservés aux femmes ?": "Are your trips reserved for women?",
  "Voyage accompagnée": "Accompanied travel",
  "Voyages 100% femmes au Maroc, organisés avec transport, activités et accompagnement.": "100% women's trips in Morocco, organized with transport, activities and support.",
  "Voyages à venir": "Upcoming trips",
  "Voyages entre femmes": "Trips between women",
  "Voyageuse allongée sur une dune à côté du drapeau EcoTrips Women": "Traveller lying on a dune next to the EcoTrips Women flag",
  "Voyageuse au sommet du Toubkal en hiver": "Traveller at the summit of Toubkal in winter",
  "Voyageuse en combinaison de ski dans la neige": "Traveller in a ski suit in the snow",
  "Voyageuse posant au panneau du sommet du Jbel Karbou": "Traveller posing by the Jbel Karbou summit sign",
  "Voyageuse sur un pont au-dessus d'une rivière turquoise": "Traveller on a bridge over a turquoise river",
  "Voyageuse sur un pont au-dessus d'une rivière turquoise en montagne": "Traveller on a bridge over a turquoise river in the mountains",
  "Voyageuses réunies au sommet du Monte Blanco face à la baie": "Travellers gathered at the top of Monte Blanco overlooking the bay",
  "Voyageuses satisfaites": "Satisfied travellers",
};
